-- ============================================================================
-- SQL PATCH: FIX ALL REPORTED ERRORS & ADD MISSING FEATURES
-- ============================================================================
-- Run this ENTIRE script in your Supabase SQL Editor (one shot).
-- Safe to run multiple times (uses IF NOT EXISTS / IF EXISTS).
-- ============================================================================

-- ╔═══════════════════════════════════════════════════════════════════════╗
-- ║  1. إصلاح جدول الموظفين - إضافة أعمدة المستمسكات الرسمية           ║
-- ╚═══════════════════════════════════════════════════════════════════════╝
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS national_id_url TEXT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS residency_card_url TEXT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS marriage_contract_url TEXT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS ration_card_url TEXT;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS theme_preference TEXT DEFAULT 'light';

-- ╔═══════════════════════════════════════════════════════════════════════╗
-- ║  2. إصلاح كتب الشكر والعقوبات - إزالة القيد المقيد                 ║
-- ╚═══════════════════════════════════════════════════════════════════════╝
ALTER TABLE public.appreciation_letters DROP CONSTRAINT IF EXISTS appreciation_letters_bonus_months_check;

-- ╔═══════════════════════════════════════════════════════════════════════╗
-- ║  3. إصلاح نظام الإعلانات - عداد المشاهدات                          ║
-- ╚═══════════════════════════════════════════════════════════════════════╝
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS view_count INT DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.announcement_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id UUID REFERENCES public.announcements(id) ON DELETE CASCADE,
    employee_id UUID REFERENCES public.employees(id) ON DELETE CASCADE,
    viewed_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(announcement_id, employee_id)
);

ALTER TABLE public.announcement_views DISABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.record_announcement_view(ann_id UUID, emp_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO public.announcement_views (announcement_id, employee_id)
    VALUES (ann_id, emp_id)
    ON CONFLICT (announcement_id, employee_id) DO NOTHING;

    UPDATE public.announcements
    SET view_count = (
        SELECT COUNT(*)
        FROM public.announcement_views
        WHERE announcement_id = ann_id
    )
    WHERE id = ann_id;
END;
$$;

-- ╔═══════════════════════════════════════════════════════════════════════╗
-- ║  4. إصلاح إعدادات الموظف - تغيير الصورة وكلمة المرور               ║
-- ╚═══════════════════════════════════════════════════════════════════════╝
CREATE OR REPLACE FUNCTION public.update_employee_settings(
    p_employee_id UUID,
    p_avatar_url TEXT DEFAULT NULL,
    p_visible_password TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE public.employees
    SET
        avatar_url = COALESCE(p_avatar_url, avatar_url),
        visible_password = COALESCE(p_visible_password, visible_password)
    WHERE id = p_employee_id;
END;
$$;

-- ╔═══════════════════════════════════════════════════════════════════════╗
-- ║  5. صلاحيات                                                         ║
-- ╚═══════════════════════════════════════════════════════════════════════╝
GRANT ALL ON public.announcement_views TO authenticated, anon, service_role;

-- ============================================================================
-- END OF PATCH
-- ============================================================================
