-- Drop table if exists to ensure clean slate (use with caution if you have existing data)
drop table if exists system_settings;

-- Create system_settings table
create table system_settings (
  id bigint primary key generated by default as identity,
  company_name text default 'MDOC HRMS',
  theme text default 'light',
  allow_password_change boolean default true,
  allow_profile_picture_change boolean default true,
  allow_backup_download boolean default false,
  login_method text default 'both', -- 'password', 'qr', 'both'
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Insert default settings
insert into system_settings (id, theme, allow_password_change, allow_profile_picture_change, allow_backup_download, login_method)
overriding system value
values (1, 'light', true, true, false, 'both');

-- Enable RLS
alter table system_settings enable row level security;

-- Policy: Admin can update settings
create policy "Admins can update settings"
  on system_settings for update
  using (auth.role() = 'authenticated'); 

-- Policy: Admin can insert settings (needed for upsert/initial creation via app)
create policy "Admins can insert settings"
  on system_settings for insert
  with check (auth.role() = 'authenticated');

-- Policy: Everyone can read settings
create policy "Everyone can read settings"
  on system_settings for select
  using (true);
